title: "Yadel Lopez"
description: "Whether you're planning a new cloud-native platform, modernizing your stack, or strengthening system reliability and observability—I can help every step of the way"
theme: jekyll-theme-cayman
author: "Yadel Lopez"
avatar: "assets/images/profile.jpg"
linkedin_username: dotnetspark
github_username: dotnetspark
email: yadel.lopez@eblsoftware.com
location: "Naples, FL"
phone: "(239) 378-3633"
